apiVersion: v1
kind: Pod
metadata:
  name: opa-allow-ns
  namespace: test2
  labels:
    owner: me.agilebank.demo
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"