apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/version: 1.0.0
    environment: dev
    helm.sh/chart: test-1.0.0
  name: test-deployment
spec:
  replicas: 100
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "3001"
        prometheus.io/scrape: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config.yaml: common/data
        vault.hashicorp.com/secret-volume-path: /config
      labels:
        app.kubernetes.io/instance: test
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: test
        app.kubernetes.io/part-of: test
        app.kubernetes.io/version: 1.0.0
        environment: dev
        helm.sh/chart: test-1.0.0
    spec:
      containers:
      - command:
        - /config/config.yaml
        env:
        - name: AWS_DEFAULT_REGION
          value: ap-northeast-2
        image: 123456789101.dkr.ecr.ap-northeast-2.amazonaws.com/test-backend:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: test
        name: test-deployment-container
        ports:
        - containerPort: 1111
          name: test
          protocol: TCP
        - containerPort: 2222
          name: test-internal
          protocol: TCP
        - containerPort: 3333
          name: test2
          protocol: TCP
        - containerPort: 4444
          name: test2-internal
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: test
        resources:
          limits:
            cpu: "1000"
            memory: 20000Mi
          requests:
            cpu: "1000"
            memory: 1000000Gi
      serviceAccountName: test-app
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/version: 1.0.0
    environment: dev
    helm.sh/chart: test-1.0.0
  name: test-service
spec:
  ports:
  - name: test1
    nodePort: null
    port: 1111
    protocol: TCP
    targetPort: test
  - name: test2
    nodePort: null
    port: 2222
    protocol: TCP
    targetPort: main-internal
  - name: test3
    nodePort: null
    port: 3333
    protocol: TCP
    targetPort: testnet
  - name: test4
    nodePort: null
    port: 4444
    protocol: TCP
    targetPort: test-internal
  selector:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
  type: ClusterIP
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/version: 1.0.0
    environment: dev
    helm.sh/chart: test-1.0.0
  name: test-hpa
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test