apiVersion: v1
kind: Pod
metadata:
  name: cpu-limit-too-high
  namespace: production
  labels:
    owner: me.agilebank.demo
spec:
  containers:
    - name: cpu-limit-too-high
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        limits:
          cpu: "3000m"
          memory: "50Mi"
        requests:
          cpu: "50m"
          memoty: "50Mi"