apiVersion: v1
kind: Pod
metadata:
  name: no-limit-cpu
  namespace: production
  labels:
    owner: me.agilebank.demo
spec:
  containers:
    - name: no-limit-cpu
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        requests:
          cpu: "50m"
          memoty: "50Mi"