apiVersion: v1
kind: Pod
metadata:
  name: no-resource
  namespace: production
  labels:
    owner: me.agilebank.demo
spec:
  containers:
    - name: no-resource
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"